- name: Setup MSYS2
  # You may pin to the exact commit or the version.
  # uses: msys2/setup-msys2@5beef6d11f48bba68b9eb503e3adc60b23c0cc36
  uses: msys2/setup-msys2@v2
  with:
    # Variant of the environment to set by default: MSYS, MINGW32, MINGW64, UCRT64, CLANG32, CLANG64 or CLANGARM64
    msystem: # optional, default is MINGW64
    # Default value for MSYS2_PATH_TYPE environment variable: strict, inherit or minimal
    path-type: # optional, default is minimal
    # Update MSYS2 installation through pacman
    update: # optional
    # After installation and/or update, install additional packages through pacman
    install: # optional
    # After installation and/or update, install additional packages through pacboy
    pacboy: # optional
    # Retrieve and extract base installation from upstream GitHub Releases
    release: # optional, default is true
    # Where to install MSYS2
    location: # optional, default is RUNNER_TEMP
    # What to do when run on an incompatible runner: fatal, warn
    platform-check-severity: # optional, default is fatal
